/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';

  static const IconData help = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_down = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData about = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData achievements = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData alumni = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData courses = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData department = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData mail = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData vision = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData mission = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData phone_outlined =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData settings_outlined =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData mail_outlined = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData location_outlined =
      IconData(0xe814, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData menu = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData close = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData placement = IconData(0xe819, fontFamily: _kFontFam);
}
